export const SEND_USER_DATA = "SEND_USER_DATA"
export const USER_DATA_SENT = "USER_DATA_SENT"
export const USER_DATA_SENDING_FAILED = "USER_DATA_SENDING_FAILED "
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"